version: "2.2"

services:
  product:
    image: ducas/elastic-rally:0.11.0
    environment:
      USER_TAG: loadtest:current ES Dev version 5.6.8 ProductTrack
    command: esrally race --pipeline benchmark-only --target-hosts ${ES_HOSTNAME} --user-tag $USER_TAG_PRODUCT:" clients=${ES_CLIENTS} duration=${ES_DURATION} throughput(TPS per client)=${ES_THROUGHPUT}" --track-path /usr/rally/product --track-params duration:${ES_DURATION},clients:${ES_CLIENTS},throughput:${ES_THROUGHPUT} --report-file=/usr/rally/results/product_result.md
    #command: sh
    volumes:
      - ./rally.ini:/root/.rally/rally.ini
      - ./tracks:/usr/rally
      - ./results:/usr/rally/results

  review:
    image: ducas/elastic-rally:0.11.0
    environment:
      USER_TAG: loadtest:current ES Dev version 5.6.8 ProductReviewTrack
    command: esrally --pipeline benchmark-only --target-hosts ${ES_HOSTNAME} --user-tag $USER_TAG_REVIEW:" clients=${ES_CLIENTS} duration=${ES_DURATION} throughput(TPS per client)=${ES_THROUGHPUT}" --track-path /usr/rally/review --track-params duration:${ES_DURATION},clients:${ES_CLIENTS},throughput:${ES_THROUGHPUT} --report-format=csv --report-file=/usr/rally/results/review_result.csv
    volumes:
      - ./rally.ini:/root/.rally/rally.ini
      - ./tracks:/usr/rally
      - ./data:/usr/rally/data
      - ./results:/usr/rally/results

  # suggestion: 
  #   image: ducas/elastic-rally:0.11.0
  #   environment:
  #     USER_TAG: loadtest:current ES Dev version 5.6.8 SuggestionTrack
  #   command: esrally --pipeline benchmark-only --target-hosts ${ES_HOSTNAME} --user-tag $USER_TAG_SUGGESTION:" clients=${ES_CLIENTS} duration=${ES_DURATION} throughput(TPS per client)=${ES_THROUGHPUT}" --track-path /usr/rally/suggestion --track-params duration:${ES_DURATION},clients:${ES_CLIENTS},throughput:${ES_THROUGHPUT} --report-format=csv --report-file=/usr/rally/results/suggestion_result.csv
  #   volumes:
  #     - ./rally.ini:/root/.rally/rally.ini
  #     - ./tracks:/usr/rally
  #     - ./data:/usr/rally/data
  #     - ./results:/usr/rally/results

  aggregate:
    image: ducas/elastic-rally:0.11.0
    environment:
      USER_TAG: loadtest:current ES Dev version 5.6.8 AggregateTrack
    command: esrally --pipeline benchmark-only --target-hosts ${ES_HOSTNAME} --user-tag $USER_TAG_AGGREGATE:" clients=${ES_CLIENTS} duration=${ES_DURATION} throughput(TPS per client)=${ES_THROUGHPUT}" --track-path /usr/rally/aggregate --track-params duration:${ES_DURATION},clients:${ES_CLIENTS},throughput:${ES_THROUGHPUT} --report-format=csv --report-file=/usr/rally/results/aggregate_result.csv
    volumes:
      - ./rally.ini:/root/.rally/rally.ini
      - ./tracks:/usr/rally
      - ./data:/usr/rally/data
      - ./results:/usr/rally/results

  category:
    image: ducas/elastic-rally:0.11.0
    environment:
      USER_TAG: loadtest:current ES Dev version 5.6.8 CategoryTrack
    command: esrally --pipeline benchmark-only --target-hosts ${ES_HOSTNAME} --user-tag $USER_TAG_CATEGORY:" clients=${ES_CLIENTS} duration=${ES_DURATION} throughput(TPS per client)=${ES_THROUGHPUT}" --track-path /usr/rally/category --track-params duration:${ES_DURATION},clients:${ES_CLIENTS},throughput:${ES_THROUGHPUT} --report-format=csv --report-file=/usr/rally/results/category_result.csv
    volumes:
      - ./rally.ini:/root/.rally/rally.ini
      - ./tracks:/usr/rally
      - ./data:/usr/rally/data
      - ./results:/usr/rally/results